config/routes.rb
Rails.application.routes.draw do
  resources :devices#, only: [:index, :create]
  resources :measurements
  resources :movements do
  	delete :delete_all, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/movement.rb
class Movement < ApplicationRecord
  after_create :notify

  def notify
    data = {
      title: 'Movement detected',
      subtitle: 'Please review this alert ASAP!',
      movement: {
        sensor: self.sensor,
        created_at: self.created_at.to_s
      }
    }
    Device.all.each do |device|
      if device.ios?
        payload = {
          :other => data,
          :"content-available" => 1
        }
        NotificationService::PushNotification.send(:ios, device.token, payload)
      elsif device.android?
        NotificationService::PushNotification.send(:android, device.token, data)
      end
    end
  end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session, only: [:index, :create, :delete_all]

  # GET /movements
  # GET /movements.json
  def index
    time_now = Time.zone.now
    @movements = Movement.where('? <= created_at AND created_at < ?', time_now.beginning_of_day, time_now.end_of_day)
  end

  # GET /movements/1
  # GET /movements/1.json
  def show
  end

  # GET /movements/new
  def new
    @movement = Movement.new
  end

  # GET /movements/1/edit
  def edit
  end

  # POST /movements
  # POST /movements.json
  def create
    @movement = Movement.new(movement_params)

    respond_to do |format|
      if @movement.save
        format.html { redirect_to @movement, notice: 'Movement was successfully created.' }
        format.json { render :show, status: :created, location: @movement }
      else
        format.html { render :new }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movements/1
  # PATCH/PUT /movements/1.json
  def update
    respond_to do |format|
      if @movement.update(movement_params)
        format.html { redirect_to @movement, notice: 'Movement was successfully updated.' }
        format.json { render :show, status: :ok, location: @movement }
      else
        format.html { render :edit }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1
  # DELETE /movements/1.json
  def destroy
    @movement.destroy
    respond_to do |format|
      format.html { redirect_to movements_url, notice: 'Movement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def delete_all
     Movement.destroy_all
     respond_to do |format|
       format.html { redirect_to movements_url, notice: 'All Movements was successfully destroyed.' }
       format.json { head :no_content }
     end
   end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movement = Movement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movement_params
      params.require(:movement).permit(:value, :sensor)
    end
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/movements/_form.html.erb
<%= form_with(model: movement, local: true) do |form| %>
  <% if movement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movement.errors.count, "error") %> prohibited this movement from being saved:</h2>

      <ul>
      <% movement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :movement_value %>
  </div>

  <div class="field">
    <%= form.label :temperature %>
    <%= form.text_field :temperature, id: :movement_temperature %>
  </div>

  <div class="field">
    <%= form.label :humidity %>
    <%= form.text_field :humidity, id: :movement_humidity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movements/edit.html.erb
<h1>Editing Movement</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Show', @movement %> |
<%= link_to 'Back', movements_path %>

app/views/movements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movements</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Temperature</th>
      <th>Humidity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movements.each do |movement| %>
      <tr>
        <td><%= movement.value %></td>
        <td><%= movement.temperature %></td>
        <td><%= movement.humidity %></td>
        <td><%= link_to 'Show', movement %></td>
        <td><%= link_to 'Edit', edit_movement_path(movement) %></td>
        <td><%= link_to 'Destroy', movement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movement', new_movement_path %>

app/views/movements/new.html.erb
<h1>New Movement</h1>

<%= render 'form', movement: @movement %>

<%= link_to 'Back', movements_path %>

app/views/movements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @movement.value %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @movement.temperature %>
</p>

<p>
  <strong>Humidity:</strong>
  <%= @movement.humidity %>
</p>

<%= link_to 'Edit', edit_movement_path(@movement) %> |
<%= link_to 'Back', movements_path %>