config/routes.rb
Rails.application.routes.draw do
  resources :devices#, only: [:index, :create]
  resources :measurements
  resources :movements do
  	delete :delete_all, on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/measurement.rb
class Measurement < ApplicationRecord
  after_create :send_to_firebase

  def send_to_firebase
    base_uri = ENV['FIREBASE_BASE_URI'] || 'https://housealert-daf2e.firebaseio.com/'
    secret_key = ENV['FIREBASE_DB_SECRET_KEY'] || 'UQr4hWos3F1nqim2IIxzO7LRIDumo4rFcXp1urib'

    firebase = Firebase::Client.new(base_uri, secret_key)

    firebase.set('last_humidity_percentage', self.humidity.to_f)
    firebase.set('last_temperature_celcius', self.temperature.to_f)

    today_averages_hash = today_averages
    firebase.set('today_humidity_percentage', today_averages_hash[:humidity_percentage_averages])
    firebase.set('today_temperature_celcius', today_averages_hash[:temperature_averages])
  end

  def today_averages
    humidity_percentage_averages = []
    temperature_averages = []
    measurements = []
    time_now = Time.zone.now
    (time_now.beginning_of_day.to_i .. time_now.to_i).step(1.hour) do |date|
      time = Time.at(date)
      if time <= time_now
        measurements = Measurement.where('? <= created_at AND created_at < ?', time, time + 1.hour)
        temperatures = measurements.map(&:temperature).map(&:to_f)
        humidity_percentages = measurements.map(&:humidity).map(&:to_f)
        temperature_averages << (temperatures.empty? ? 0 : (temperatures.inject(:+) / temperatures.size))
        humidity_percentage_averages << (humidity_percentages.empty? ? 0 : (humidity_percentages.inject(:+) / humidity_percentages.size))
      end
    end
    return { humidity_percentage_averages: humidity_percentage_averages, temperature_averages: temperature_averages }
  end

end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session, only: [:index, :create, :delete_all]

  # GET /measurements
  # GET /measurements.json
  def index
    time_now = Time.zone.now
    @measurements = Measurement.where('? <= created_at AND created_at < ?', time_now.beginning_of_day, time_now.end_of_day)
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
  end

  # GET /measurements/new
  def new
    @measurement = Measurement.new
  end

  # GET /measurements/1/edit
  def edit
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = Measurement.new(measurement_params)

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully created.' }
        format.json { render :show, status: :created, location: @measurement }
      else
        format.html { render :new }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurements/1
  # PATCH/PUT /measurements/1.json
  def update
    respond_to do |format|
      if @measurement.update(measurement_params)
        format.html { redirect_to @measurement, notice: 'Measurement was successfully updated.' }
        format.json { render :show, status: :ok, location: @measurement }
      else
        format.html { render :edit }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement.destroy
    respond_to do |format|
      format.html { redirect_to measurements_url, notice: 'Measurement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurement_params
      params.require(:measurement).permit(:temperature, :humidity, :sensor)
    end
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/measurements/_form.html.erb
<%= form_with(model: measurement, local: true) do |form| %>
  <% if measurement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(measurement.errors.count, "error") %> prohibited this measurement from being saved:</h2>

      <ul>
      <% measurement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :temperature %>
    <%= form.text_field :temperature, id: :measurement_temperature %>
  </div>

  <div class="field">
    <%= form.label :humidity %>
    <%= form.text_field :humidity, id: :measurement_humidity %>
  </div>

  <div class="field">
    <%= form.label :sensor %>
    <%= form.text_field :sensor, id: :measurement_sensor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/measurements/edit.html.erb
<h1>Editing Measurement</h1>

<%= render 'form', measurement: @measurement %>

<%= link_to 'Show', @measurement %> |
<%= link_to 'Back', measurements_path %>

app/views/measurements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Measurements</h1>

<table>
  <thead>
    <tr>
      <th>Temperature</th>
      <th>Humidity</th>
      <th>Sensor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @measurements.each do |measurement| %>
      <tr>
        <td><%= measurement.temperature %></td>
        <td><%= measurement.humidity %></td>
        <td><%= measurement.sensor %></td>
        <td><%= link_to 'Show', measurement %></td>
        <td><%= link_to 'Edit', edit_measurement_path(measurement) %></td>
        <td><%= link_to 'Destroy', measurement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Measurement', new_measurement_path %>

app/views/measurements/new.html.erb
<h1>New Measurement</h1>

<%= render 'form', measurement: @measurement %>

<%= link_to 'Back', measurements_path %>

app/views/measurements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Temperature:</strong>
  <%= @measurement.temperature %>
</p>

<p>
  <strong>Humidity:</strong>
  <%= @measurement.humidity %>
</p>

<p>
  <strong>Sensor:</strong>
  <%= @measurement.sensor %>
</p>

<%= link_to 'Edit', edit_measurement_path(@measurement) %> |
<%= link_to 'Back', measurements_path %>